initVancouver = [
  {
    bathrooms: 3,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/2165353fd41deb3110bb8ac2a15c0187-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.2632,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 2922,
    longitude: -123.04304,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5227.2,
    openHouse: 'Thu. 5-7pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689300000000,
          open_house_start: 1689292800000,
        },
        {
          open_house_end: 1689458400000,
          open_house_start: 1689447600000,
        },
        {
          open_house_end: 1689544800000,
          open_house_start: 1689534000000,
        },
      ],
    },
    price: 1998000,
    priceForHDP: 1998000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2933 E 8th Ave',
    taxAssessedValue: 1649000,
    zipcode: 'V5M1X2',
    zpid: 314404079,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/1cba59e231a700ba8c566913bb1ab945-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.213608,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 1355,
    longitude: -123.06892,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4791.6,
    price: 1799000,
    priceForHDP: 1799000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '7776 Jasper Cres',
    taxAssessedValue: 1418700,
    zipcode: 'V5P3S9',
    zpid: 314422398,
  },
  {
    bathrooms: 4,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/622c2d9f0173df68856c4ebb756b02d9-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.235703,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 5065,
    longitude: -123.14958,
    lotAreaUnit: 'sqft',
    lotAreaValue: 9147.6,
    price: 5298000,
    priceForHDP: 5298000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '5583 Cypress St',
    taxAssessedValue: 5084000,
    zipcode: 'V6M3R5',
    zpid: 314346453,
  },
  {
    bathrooms: 7,
    bedrooms: 7,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/9becdecd8266bbb50491d3bcf17d3380-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.21759,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 5513,
    longitude: -123.13572,
    lotAreaUnit: 'sqft',
    lotAreaValue: 9147.6,
    price: 5380000,
    priceForHDP: 5380000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1331 W 59th Ave',
    taxAssessedValue: 5014000,
    zipcode: 'V6P1Y6',
    zpid: 314355226,
  },
  {
    bathrooms: 8,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/b564d48d64a0a89554a18c9cce73aadb-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.237865,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 4096,
    longitude: -123.19032,
    lotAreaUnit: 'sqft',
    lotAreaValue: 6969.6,
    price: 6899000,
    priceForHDP: 6899000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '3877 W 38th Ave',
    taxAssessedValue: 4923000,
    zipcode: 'V6N2Y5',
    zpid: 314335222,
  },
  {
    bathrooms: 7,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/94f115b4aca681be9b52d6914408f557-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.222336,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 4489,
    longitude: -123.121185,
    lotAreaUnit: 'sqft',
    lotAreaValue: 6534,
    price: 5200000,
    priceForHDP: 5200000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '720 W 53rd Ave',
    taxAssessedValue: 4074000,
    zipcode: 'V6P1K4',
    zpid: 314357427,
  },
  {
    bathrooms: 2,
    bedrooms: 4,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/253d176fb527410abf7f872ade38b215-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.234436,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2165,
    longitude: -123.17133,
    lotAreaUnit: 'sqft',
    lotAreaValue: 435.6,
    price: 2890000,
    priceForHDP: 2890000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2936 W 41st Ave',
    taxAssessedValue: 1871600,
    zipcode: 'V6N3C7',
    zpid: 314341432,
  },
  {
    bathrooms: 6,
    bedrooms: 9,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/1854758491202dd7e7cd0cbf46df1238-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.241676,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 5001,
    longitude: -123.18173,
    lotAreaUnit: 'sqft',
    lotAreaValue: 8276.4,
    price: 4350000,
    priceForHDP: 4350000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '3491 W 34th Ave',
    taxAssessedValue: 3760000,
    zipcode: 'V6N2K5',
    zpid: 314334689,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/4ded9bdca39ad5da40dc05b47003387e-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.26699,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 1620,
    longitude: -123.061584,
    lotAreaUnit: 'sqft',
    lotAreaValue: 2613.6,
    price: 2498000,
    priceForHDP: 2498000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1946 Lakewood Dr',
    taxAssessedValue: 1320900,
    zipcode: 'V5N4T5',
    zpid: 314366186,
  },
  {
    bathrooms: 3,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/36b54e25183c2705ce0d7b52c546f85a-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.228214,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2717,
    longitude: -123.082275,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5662.8,
    price: 2490000,
    priceForHDP: 2490000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '6170 Ross St',
    taxAssessedValue: 1691200,
    zipcode: 'V5W3L6',
    zpid: 314389879,
  },
  {
    bathrooms: 5,
    bedrooms: 8,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/10585d688ff9508939b3b9217cfda590-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.25296,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 3516,
    longitude: -123.05505,
    lotAreaUnit: 'sqft',
    lotAreaValue: 3484.8,
    price: 3298000,
    priceForHDP: 3298000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2460 E 19th Ave',
    taxAssessedValue: 1224400,
    zipcode: 'V5M2R9',
    zpid: 314407189,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/d92e73d3e93553aa441f883c6c0c7307-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.220184,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2200,
    longitude: -123.07689,
    lotAreaUnit: 'sqft',
    lotAreaValue: 3484.8,
    price: 1628000,
    priceForHDP: 1628000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1426 E 54th Ave',
    taxAssessedValue: 1381900,
    zipcode: 'V5P1Y1',
    zpid: 314385316,
  },
  {
    bathrooms: 7,
    bedrooms: 8,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc:
      'https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=49.2437629699707,-123.04153442382812&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=tfGF2KVOB74TFWvHd0qDnjDHj1I=',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.243763,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 3031,
    longitude: -123.041534,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    openHouse: 'Sat. 2-4pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689462000000,
          open_house_start: 1689454800000,
        },
        {
          open_house_end: 1689548400000,
          open_house_start: 1689541200000,
        },
      ],
    },
    price: 2200000,
    priceForHDP: 2200000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '4569 Moss St',
    taxAssessedValue: 1634000,
    zipcode: 'V5R3S9',
    zpid: 314411621,
  },
  {
    bathrooms: 3,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/7197497f9fbe0d1d7bc6787d2168a5ac-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.261627,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 2465,
    longitude: -123.20239,
    lotAreaUnit: 'sqft',
    lotAreaValue: 6534,
    openHouse: 'Sat. 2-4pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689462000000,
          open_house_start: 1689454800000,
        },
        {
          open_house_end: 1689548400000,
          open_house_start: 1689541200000,
        },
      ],
    },
    price: 4088000,
    priceForHDP: 4088000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '4278 W 12th Ave',
    taxAssessedValue: 3370800,
    zipcode: 'V6R2P7',
    zpid: 314321568,
  },
  {
    bathrooms: 5,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/c3441969e64a5e72c78c9813c003566c-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.22083,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 2767,
    longitude: -123.051384,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    openHouse: 'Sat. 2-4pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689462000000,
          open_house_start: 1689454800000,
        },
        {
          open_house_end: 1689548400000,
          open_house_start: 1689541200000,
        },
      ],
    },
    price: 2599900,
    priceForHDP: 2599900,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2778 E 53rd Ave',
    taxAssessedValue: 2005000,
    zipcode: 'V5S1W2',
    zpid: 314422128,
  },
  {
    bathrooms: 6,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/7197497f9fbe0d1d7bc6787d2168a5ac-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.235977,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 3988,
    longitude: -123.1873,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5227.2,
    price: 4860000,
    priceForHDP: 4860000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '5558 Alma St',
    taxAssessedValue: 3513000,
    zipcode: 'V6N1Y2',
    zpid: 314330235,
  },
  {
    bathrooms: 6,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/1f4ef27ff2d38c84f6948286407fc8ec-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.246384,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 3046,
    longitude: -123.174576,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    openHouse: 'Sat. 2-4pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689462000000,
          open_house_start: 1689454800000,
        },
        {
          open_house_end: 1689548400000,
          open_house_start: 1689541200000,
        },
      ],
    },
    price: 4460000,
    priceForHDP: 4460000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '3115 W 29th Ave',
    taxAssessedValue: 2539000,
    zipcode: 'V6L1Y5',
    zpid: 314338577,
  },
  {
    bathrooms: 3,
    bedrooms: 7,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/8b4450575192717dd88ad1584e35134a-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.288975,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 2993,
    longitude: -123.04603,
    lotAreaUnit: 'sqft',
    lotAreaValue: 3920.4,
    openHouse: 'Sat. 3-5pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689465600000,
          open_house_start: 1689458400000,
        },
        {
          open_house_end: 1689552000000,
          open_house_start: 1689544800000,
        },
      ],
    },
    price: 1559000,
    priceForHDP: 1559000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2815 McGill St',
    taxAssessedValue: 1238600,
    zipcode: 'V5K1H7',
    zpid: 314396577,
  },
  {
    bathrooms: 5,
    bedrooms: 4,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/abd48a0290a4d5de0e1ddc3f576abf51-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.2136,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2759,
    longitude: -123.10766,
    lotAreaUnit: 'sqft',
    lotAreaValue: 3920.4,
    price: 3150000,
    priceForHDP: 3150000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '43 W 63rd Ave',
    taxAssessedValue: 1830000,
    zipcode: 'V5X2H7',
    zpid: 314360407,
  },
  {
    bathrooms: 2,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc:
      'https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=49.231109619140625,-123.15431213378906&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=iHB90cxAScX0lsLvSUvQzZiUfKI=',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.23111,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2483,
    longitude: -123.15431,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    price: 2688000,
    priceForHDP: 2688000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2085 W 45th Ave',
    taxAssessedValue: 2301000,
    zipcode: 'V6M2H8',
    zpid: 314342089,
  },
  {
    bathrooms: 3,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/068fe9e43aaaa6465aa79537635edd99-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.23676,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 3222,
    longitude: -123.08059,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    price: 2199999,
    priceForHDP: 2199999,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '5269 Inverness St',
    taxAssessedValue: 1683000,
    zipcode: 'V5W3N9',
    zpid: 314390419,
  },
  {
    bathrooms: 2,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/4dfdad8174eccbc0d385743e9cabc891-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.25583,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2456,
    longitude: -123.18636,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4791.6,
    price: 3088000,
    priceForHDP: 3088000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '3663 W 19th Ave',
    taxAssessedValue: 2626200,
    zipcode: 'V6S1C5',
    zpid: 314332075,
  },
  {
    bathrooms: 4,
    bedrooms: 4,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc:
      'https://maps.googleapis.com/maps/api/staticmap?mobile=false&sensor=true&maptype=satellite&size=575x242&zoom=17&center=49.25309371948242,-123.17974090576172&key=AIzaSyBJsNQO5ZeG-XAbqqWLKwG08fWITSxg33w&signature=b0WdB5WxDPmVTj53otYre5aHoUc=',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.253094,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2412,
    longitude: -123.17974,
    lotAreaUnit: 'sqft',
    lotAreaValue: 3920.4,
    price: 2795000,
    priceForHDP: 2795000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '3355 W 22nd Ave',
    taxAssessedValue: 2578000,
    zipcode: 'V6S1J1',
    zpid: 314332759,
  },
  {
    bathrooms: 3,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/6c48fa5473970762e64ddf5bc3a8abc9-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.253487,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 3225,
    longitude: -123.09262,
    lotAreaUnit: 'sqft',
    lotAreaValue: 1,
    openHouse: 'Wed. 6-7pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689213600000,
          open_house_start: 1689210000000,
        },
        {
          open_house_end: 1689282000000,
          open_house_start: 1689274800000,
        },
        {
          open_house_end: 1689462000000,
          open_house_start: 1689454800000,
        },
        {
          open_house_end: 1689548400000,
          open_house_start: 1689541200000,
        },
      ],
    },
    price: 2398000,
    priceForHDP: 2398000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '568 E 19th Ave',
    taxAssessedValue: 1745000,
    zipcode: 'V5V1J9',
    zpid: 314373743,
  },
  {
    bathrooms: 6,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/6adeedc65f865571e3362df393a14176-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.222473,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 5178,
    longitude: -123.12943,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.4,
    price: 4999900,
    priceForHDP: 4999900,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1052 W 53rd Ave',
    taxAssessedValue: 4482000,
    zipcode: 'V6P1K7',
    zpid: 314354753,
  },
  {
    bathrooms: 8,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/7c8ceaf046b0e7f411f9214272a75281-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.237804,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 7415,
    longitude: -123.14572,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.29,
    price: 10500000,
    priceForHDP: 10500000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1768 W 37th Ave',
    taxAssessedValue: 7674000,
    zipcode: 'V6M1N1',
    zpid: 314348240,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/f8e52fc056c066ef2c5e38a0291e8c49-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.225914,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 3044,
    longitude: -123.14759,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    openHouse: 'Sat. 2-4pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689462000000,
          open_house_start: 1689454800000,
        },
      ],
    },
    price: 3280000,
    priceForHDP: 3280000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '6580 Angus Dr',
    taxAssessedValue: 2421000,
    zipcode: 'V6P5H9',
    zpid: 314352753,
  },
  {
    bathrooms: 3,
    bedrooms: 7,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/dcc214f8da587e0ac00e17d4f6bc0cfe-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.278866,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2838,
    longitude: -123.06262,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    price: 1025000,
    priceForHDP: 1025000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2044 Turner St',
    zipcode: 'V5L2A3',
    zpid: 2057534227,
  },
  {
    bathrooms: 11,
    bedrooms: 7,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/400e28b8b0dbcc4b0ce16dd86f75f433-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.257328,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 10335,
    longitude: -123.13345,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.5700000000000001,
    price: 19880000,
    priceForHDP: 19880000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1233 Tecumseh Ave',
    taxAssessedValue: 9177000,
    zipcode: 'V6H1T3',
    zpid: 314347206,
  },
  {
    bathrooms: 8,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/df77e8aff89a97a5719d7b78c08fe06c-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.27489,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 12410,
    longitude: -123.22121,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.85,
    price: 59800000,
    priceForHDP: 59800000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '4838 Belmont Ave',
    taxAssessedValue: 17339000,
    zipcode: 'V6T1A9',
    zpid: 314319398,
  },
  {
    bathrooms: 11,
    bedrooms: 7,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/ce37f98441b06a49919b3a94dc274eb9-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.274914,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 10548,
    longitude: -123.21983,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.61,
    price: 33888000,
    priceForHDP: 33888000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '4788 Belmont Ave',
    taxAssessedValue: 21511000,
    zipcode: 'V6T1A9',
    zpid: 314319401,
  },
  {
    bathrooms: 6,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/cdbf90c4efc2ce2a92953ca21ca2c903-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.270454,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 4299,
    longitude: -123.20624,
    lotAreaUnit: 'sqft',
    lotAreaValue: 6098.4,
    price: 11880000,
    priceForHDP: 11880000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '4407 W 3rd Ave',
    taxAssessedValue: 4477000,
    zipcode: 'V6R1M9',
    zpid: 314319870,
  },
  {
    bathrooms: 5,
    bedrooms: 4,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/5df6c92f7fad144229a0bcb662931194-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.273804,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 5986,
    longitude: -123.1618,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5662.8,
    price: 22880000,
    priceForHDP: 22880000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2495 Point Grey Rd',
    taxAssessedValue: 15858000,
    zipcode: 'V6K1A1',
    zpid: 314324177,
  },
  {
    bathrooms: 9,
    bedrooms: 6,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/c23494f78f1384ee14fd3bc65d8c74a4-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.255585,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 9714,
    longitude: -123.13185,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.54,
    price: 21990000,
    priceForHDP: 21990000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '3402 Osler St',
    taxAssessedValue: 20401000,
    zipcode: 'V6H2W3',
    zpid: 314346938,
  },
  {
    bathrooms: 6,
    bedrooms: 4,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/8bf584095b5aef9e842a9daea6d84850-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.275955,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 4866,
    longitude: -123.14791,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4356,
    price: 6980000,
    priceForHDP: 6980000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1133 Cypress St',
    taxAssessedValue: 5935000,
    zipcode: 'V6J3K8',
    zpid: 314323922,
  },
  {
    bathrooms: 12,
    bedrooms: 8,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/31407f2e34f6688bb903780099b79fbc-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.22012,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 15371,
    longitude: -123.13219,
    lotAreaUnit: 'acres',
    lotAreaValue: 1.05,
    price: 28880000,
    priceForHDP: 28880000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1188 W 55th Ave',
    taxAssessedValue: 18846000,
    zipcode: 'V6P1R1',
    zpid: 314354869,
  },
  {
    bathrooms: 2,
    bedrooms: 2,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/f5648fa18dd12796a78283091e437657-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.29139,
    listing_sub_type: {
      is_FSBA: true,
      is_openHouse: true,
    },
    livingArea: 1192,
    longitude: -123.12772,
    lotAreaUnit: 'sqft',
    lotAreaValue: 0.01,
    openHouse: '7/19 3:30-5:30pm',
    open_house_info: {
      open_house_showing: [
        {
          open_house_end: 1689813000000,
          open_house_start: 1689805800000,
        },
      ],
    },
    price: 1225000,
    priceForHDP: 1225000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1525 Coal Harbour Cay #C38',
    unit: '# C38',
    zipcode: 'V6G3E7',
    zpid: 2067687363,
  },
  {
    bathrooms: 5,
    bedrooms: 4,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/2bc0f50fb9da69bada96148cb65a127f-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.2363,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 2888,
    longitude: -123.1667,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4791.6,
    price: 2998000,
    priceForHDP: 2998000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '2738 W 39th Ave',
    taxAssessedValue: 2585000,
    zipcode: 'V6N2Z4',
    zpid: 314341365,
  },
  {
    bathrooms: 8,
    bedrooms: 5,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/0aab0eb9a7de5bfcd355f13966686fdc-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.25113,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 8824,
    longitude: -123.13544,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.45999999999999996,
    price: 23880000,
    priceForHDP: 23880000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '1351 Laurier Ave',
    taxAssessedValue: 13796000,
    zipcode: 'V6H1Y9',
    zpid: 314347556,
  },
  {
    bathrooms: 10,
    bedrooms: 7,
    city: 'Vancouver',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/825b64d60c158a2958131710278e5c31-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 49.22908,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 9070,
    longitude: -123.16667,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.49000000000000005,
    price: 26888000,
    priceForHDP: 26888000,
    shouldHighlight: false,
    state: 'BC',
    streetAddress: '6330 Macdonald St',
    taxAssessedValue: 11186000,
    zipcode: 'V6N1E6',
    zpid: 314342949,
  },
];

const initToronto = [
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/c9a3bc96379197ed69b2fd27b4002b45-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 1432,
    lotAreaUnit: 'acres',
    lotAreaValue: 0.25539345730027546,
    price: 1399000,
    priceForHDP: 1399000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '25 Devondale Ave',
    zipcode: 'M2R2C9',
    zpid: 2056968905,
  },
  {
    bathrooms: 2,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/7af2e860b656acb97e7b4335cfd796db-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.632072,
    listing_sub_type: {
      is_FSBA: true,
    },
    livingArea: 1300,
    longitude: -79.55075,
    lotAreaUnit: 'sqft',
    lotAreaValue: 4960,
    price: 1299900,
    priceForHDP: 1299900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '136 Silverhill Dr',
    zipcode: 'M9B3W7',
    zpid: 2056478825,
  },
  {
    bathrooms: 2,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/1e033ea7f891e4d32cce17fb925eec8b-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 799900,
    priceForHDP: 799900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '4 Lisa Rd W',
    zipcode: 'M1G2H9',
    zpid: 2064163514,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/fb189b22ec0adcf352ba225c6cb6a6e9-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.71836,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.5903,
    price: 899900,
    priceForHDP: 899900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '4 Mancroft Cres',
    zipcode: 'M9W3E8',
    zpid: 2056484412,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 0,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/e69440eba21cb8d699de8a5213f85a0f-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.752098,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.28499,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5250,
    price: 898000,
    priceForHDP: 898000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '21 Merryfield Dr',
    zipcode: 'M1P1J3',
    zpid: 2056482418,
  },
  {
    bathrooms: 2,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/fdbd65664e3333c5b3c59d172014297f-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.70721,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.24846,
    price: 700881,
    priceForHDP: 700881,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '7 Pell St',
    zipcode: 'M1N1M9',
    zpid: 2056484431,
  },
  {
    bathrooms: 5,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 0,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/9c17aa946a84d7ee2f9df10fce3164f8-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.69234,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.29736,
    lotAreaUnit: 'sqft',
    lotAreaValue: 3113.5034,
    price: 1199700,
    priceForHDP: 1199700,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '108 Dawes Rd',
    zipcode: 'M4C5B6',
    zpid: 2056483147,
  },
  {
    bathrooms: 4,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/06604f542983573c106fcd957524addf-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 1100000,
    priceForHDP: 1100000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '89 Barnwell Dr',
    zipcode: 'M1V1Z1',
    zpid: 2077703323,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/90b7f12b3dcbbe89358b9ec7df02fe23-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.74598,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.56108,
    price: 999900,
    priceForHDP: 999900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '167 Ardwick Blvd',
    zipcode: 'M9M1W3',
    zpid: 2056484409,
  },
  {
    bathrooms: 2,
    bedrooms: 2,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/c53065db874d46b97c60842512a1bc89-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.680687,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.463104,
    price: 979000,
    priceForHDP: 979000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '51 Rowntree Ave',
    zipcode: 'M6N1R8',
    zpid: 2056484414,
  },
  {
    bathrooms: 4,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/c4e4d135338af7786dbadd363a48fabe-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.70063,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.27351,
    price: 1098000,
    priceForHDP: 1098000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '32 Dairy Dr',
    zipcode: 'M1L0G2',
    zpid: 2056484439,
  },
  {
    bathrooms: 3,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/fa633d6ae1249ae6e6ed3f8d92791a15-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.772846,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.139,
    price: 1228800,
    priceForHDP: 1228800,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '9 Rockport Dr',
    zipcode: 'M1C5C2',
    zpid: 2056482215,
  },
  {
    bathrooms: 3,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/911f9b643de58332399158d19605c943-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.78884,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.21579,
    lotAreaUnit: 'sqft',
    lotAreaValue: 7001.4616,
    price: 788000,
    priceForHDP: 788000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '48 Highcastle Rd',
    zipcode: 'M1E4N1',
    zpid: 2056492408,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/155204763b768c19c00c2da51d1c971a-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.683628,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.539444,
    price: 1980000,
    priceForHDP: 1980000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '108 Summitcrest Dr',
    zipcode: 'M9P1H8',
    zpid: 2056484428,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/6e15bc77382c8a95e90fffd225329337-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.66187,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.47799,
    price: 1395000,
    priceForHDP: 1395000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '137 Gilmour Ave',
    zipcode: 'M6P3B2',
    zpid: 2056484417,
  },
  {
    bathrooms: 2,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/e682ee3530f2515822d3b46f5aa6c8b3-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.664715,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.44534,
    price: 819000,
    priceForHDP: 819000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '921 Lansdowne Ave',
    zipcode: 'M6H3Z2',
    zpid: 2056490407,
  },
  {
    bathrooms: 5,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/3913f0b4ad784af73295cce5db3f53aa-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.62825,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.4993,
    price: 1599000,
    priceForHDP: 1599000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '18 Moynes Ave',
    zipcode: 'M8Y3B6',
    zpid: 2056484435,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/e159f4e80721d9b77e20e442408d2908-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.768402,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.20713,
    price: 749000,
    priceForHDP: 749000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '75 Orton Park Rd',
    zipcode: 'M1G3G7',
    zpid: 2056490454,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/210464a1061889ff47d49994d8116cf8-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.650665,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.48862,
    price: 1999000,
    priceForHDP: 1999000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '72 Riverview Gdns',
    zipcode: 'M6S4E5',
    zpid: 2056484399,
  },
  {
    bathrooms: 3,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/8c86ebf90f8894ff78371140e9442abc-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 988000,
    priceForHDP: 988000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '595 Pape Ave',
    zipcode: 'M4K3R7',
    zpid: 2062747193,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/4c11ba25a36a87cfc875fd602e09540f-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 799000,
    priceForHDP: 799000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '654 Saint Clarens Ave',
    zipcode: 'M6H3W9',
    zpid: 2069491543,
  },
  {
    bathrooms: 2,
    bedrooms: 2,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/65dfb2c4bd34cc6e72c69f5068390b6a-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 699900,
    priceForHDP: 699900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '121 Kitchener Ave',
    zipcode: 'M6E2B8',
    zpid: 2081241461,
  },
  {
    bathrooms: 4,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/8814797b3bb5ba853b3d39ab97ff8dfe-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 999900,
    priceForHDP: 999900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '53 Miramar Cres',
    zipcode: 'M1J1R3',
    zpid: 2069120037,
  },
  {
    bathrooms: 4,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/50dc59f31cfb284c960b179427c3101c-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.81407,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.26118,
    price: 1198000,
    priceForHDP: 1198000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '2 Lansbury Dr',
    zipcode: 'M1V3H6',
    zpid: 2056490465,
  },
  {
    bathrooms: 6,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/7ebf67da3fa82071688f6ede751880ae-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.808105,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.286835,
    price: 1180000,
    priceForHDP: 1180000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '7 Haven Hill Sq',
    zipcode: 'M1V1M3',
    zpid: 2056497244,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/40ff66abeed2c5cdc64b9bf1d93b801d-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.687927,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.37315,
    price: 2099999,
    priceForHDP: 2099999,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '26 Edgewood Cres',
    zipcode: 'M4W3A9',
    zpid: 2056484437,
  },
  {
    bathrooms: 4,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/1f8ea81997296402364039609219c221-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.753403,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.36975,
    price: 2800000,
    priceForHDP: 2800000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '2 Elkpath Ave',
    zipcode: 'M2L2W1',
    zpid: 2056500409,
  },
  {
    bathrooms: 4,
    bedrooms: 4,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/f9d71297e80a96cbc5658392860240c9-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.788326,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.17045,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5300,
    price: 1300000,
    priceForHDP: 1300000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '8 Camor Ct',
    zipcode: 'M1C4V5',
    zpid: 2056494299,
  },
  {
    bathrooms: 4,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/33ebbfdda81fbdf0ab3e1ec65723620c-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.73978,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.2921,
    price: 1049888,
    priceForHDP: 1049888,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '1037 Warden Ave',
    zipcode: 'M1R2N9',
    zpid: 2082005819,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/f2a73da250f6506b4f3be1315c83ffc2-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.826614,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.285194,
    price: 958000,
    priceForHDP: 958000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '8 Flatwoods Dr',
    zipcode: 'M1V4H4',
    zpid: 2056490433,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/0c35fb75cc651f013076692358b189cd-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.73822,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.30549,
    price: 1060000,
    priceForHDP: 1060000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '57 Inniswood Dr',
    zipcode: 'M1R1E8',
    zpid: 2056490462,
  },
  {
    bathrooms: 3,
    bedrooms: 5,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/0efd798dfd392298b84107728a397cca-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    lotAreaUnit: 'sqft',
    lotAreaValue: 5000,
    price: 899000,
    priceForHDP: 899000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '5 Hollydene Rd',
    zipcode: 'M1L2A4',
    zpid: 2058042664,
  },
  {
    bathrooms: 2,
    bedrooms: 2,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/059308dee0e0c078d49b26563e22f83e-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.709225,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.28831,
    price: 999800,
    priceForHDP: 999800,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '136 Presley Ave',
    zipcode: 'M1L3R1',
    zpid: 2056497245,
  },
  {
    bathrooms: 2,
    bedrooms: 2,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/49ea3a70b758c86693155794f818e4ac-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 949900,
    priceForHDP: 949900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '32 Freeman St',
    zipcode: 'M1N2C1',
    zpid: 2071808153,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/cae9cfe8765b3caac351485253ef3f10-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.769592,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.2221,
    price: 999599,
    priceForHDP: 999599,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '17 Barlow Rd',
    zipcode: 'M1G2B5',
    zpid: 2056500389,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/576833b76a29593502469973913aa498-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.763405,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.51375,
    lotAreaUnit: 'sqft',
    lotAreaValue: 7203.95,
    price: 949900,
    priceForHDP: 949900,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '281 Driftwood Ave',
    zipcode: 'M3N2N6',
    zpid: 2056489976,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/b67dbcc73843ad04a85364f145d2b7a6-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.71607,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.29745,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5000,
    price: 888000,
    priceForHDP: 888000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '63 Delwood Dr',
    zipcode: 'M1L2S8',
    zpid: 2056491827,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: 1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/01e469f2b75d7a3a34d08128fd15bb49-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.66051,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.54748,
    lotAreaUnit: 'sqft',
    lotAreaValue: 5000,
    price: 1099000,
    priceForHDP: 1099000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '22 Lloyd Manor Rd',
    zipcode: 'M9B5H6',
    zpid: 2056489470,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/33613a69d5b99845c6f3c1ec224b7997-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.712753,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.36776,
    price: 1199000,
    priceForHDP: 1199000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '773 Eglinton Ave E',
    zipcode: 'M4G2K8',
    zpid: 2056490434,
  },
  {
    bathrooms: 3,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/8bf56d5127ada9cd16a43b1e59387a1c-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    listing_sub_type: {
      is_FSBA: true,
    },
    price: 950000,
    priceForHDP: 950000,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '97 Monterrey Dr',
    zipcode: 'M9V1T2',
    zpid: 2064686539,
  },
  {
    bathrooms: 2,
    bedrooms: 3,
    city: 'Toronto',
    country: 'CAN',
    currency: 'CAD',
    daysOnZillow: -1,
    homeStatus: 'FOR_SALE',
    homeStatusForHDP: 'FOR_SALE',
    homeType: 'SINGLE_FAMILY',
    imgSrc: 'https://photos.zillowstatic.com/fp/9ba8e8c3ddf4f44139044a1b522d664a-p_e.jpg',
    isFeatured: false,
    isNonOwnerOccupied: true,
    isPreforeclosureAuction: false,
    isPremierBuilder: false,
    isShowcaseListing: false,
    isUnmappable: false,
    isZillowOwned: false,
    latitude: 43.777714,
    listing_sub_type: {
      is_FSBA: true,
    },
    longitude: -79.43797,
    price: 1588888,
    priceForHDP: 1588888,
    shouldHighlight: false,
    state: 'ON',
    streetAddress: '50 Devondale Ave',
    zipcode: 'M2R2E2',
    zpid: 2056490448,
  },
];

module.exports = { initVancouver, initToronto };
